import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Sidebar from "@/components/Sidebar";
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import TopBar from "@/components/TopBar";
import HeaderPage from "@/components/Header/HeaderPage";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";


const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={roboto.variable}>
       <body>
          <AppRouterCacheProvider>
           <ThemeProvider theme={theme}>
              <TopBar />
              <Box sx={{ display: 'flex'}}>
                <Sidebar/>
                <Stack
                    spacing={2}
                    sx={{
                      width: "100%",
                      mx: 3,
                      pb: 5,
                      mt: { xs: 12, md: 0 },
                    }}
                  >
                  <HeaderPage/>
                  {children}
                </Stack>
              </Box>
           </ThemeProvider>
          </AppRouterCacheProvider>
       </body>
     </html>
  );
}
